### ISSUE TITLE
question:关于clickhouse日志告警的几个问题

### ISSUE THREAD

**Issue by ktpktr0** [clickvisual/clickvisual#1148]
1、prom2click配置，同时应该更新文档
需要将以下配置修改为0.0.0.0
[[prom2click.cfgs]]
host = "0.0.0.0"
port = 9201

2、 添加钉钉机器人有加签之类(页面测试成功，但无法收到消息，需要确认)

需要在机器人url后面加上&secret=xxx

3、环境检测部分：AlertManager 检测

刷新页面显示：”异常webhook configuration is empty: Prometheus does not configure alertmanager“，再刷新几下又恢复正常，再刷新几下交替出现。实际上prometheus已配置alertmanager地址

4、添加告警规则失败

![image](https://github.com/clickvisual/clickvisual/assets/41657218/be532ade-cea1-44d1-b854-0af17a5db3f4)

详细报错：
```
请求失败
错误：sql: CREATE MATERIALIZED VIEW IF NOT EXISTS default.job_admin_b0edc699_4d56_4652_908a_067415c9c0f8_4 TO metrics.samples AS SELECT toDate(_time_second_) as date, 'clickvisual_alert_metrics' as name, array('uuid=b0edc699-4d56-4652-908a-067415c9c0f8','alarmId=4','filterId=4') as tags, toFloat64(count(*)) as val, _time_second_ as ts, toDateTime(_time_second_) as updated FROM `default`.`job_admin` WHERE message = 'this is new' GROUP BY _time_second_;: code: 47, message: Missing columns: 'message' while processing query: 'SELECT toDate(_time_second_) AS date, 'clickvisual_alert_metrics' AS name, ['uuid=b0edc699-4d56-4652-908a-067415c9c0f8', 'alarmId=4', 'filterId=4'] AS tags, toFloat64(count()) AS val, _time_second_ AS ts, toDateTime(_time_second_) AS updated FROM default.job_admin WHERE message = 'this is new' GROUP BY _time_second_', required columns: '_time_second_' 'message', maybe you meant: '_time_second_'
```

实际是创建成功了报警规则，但告警状态是不正常的。正确应该的rules路径应该填写为：/clickvisual/rules
![image](https://github.com/clickvisual/clickvisual/assets/41657218/f93483be-c3bd-4321-b99b-3ba4a393bff2)

5、文档中prometheus配置alertmanager方式有问题

会导致告警无法传递到alertmanager

原始：
```
alerting:
  # 告警配置文件
  alertmanagers:
  # 修改：使用静态绑定
  - static_configs:
    # 修改：targets、指定地址与端口
    - targets: ["alertmanager:9093"]
 ```
正确：
```
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
```

6、clickvisual无法获取到告警状态

prome
![image](https://github.com/clickvisual/clickvisual/assets/41657218/d3b5996e-3687-47a9-9516-0b2f15e53ff2)

alert
![image](https://github.com/clickvisual/clickvisual/assets/41657218/ba0e53ec-acb1-4486-9ab8-9941082b3d57)

clickvisual

![image](https://github.com/clickvisual/clickvisual/assets/41657218/f8a0a8a0-ebdb-47f0-9255-052baa8369fd)

7、文档中关于prometheus部分是不是少了remote_write部分？
完整：
```
remote_read:
  - url: "http://clickvisual:9201/read"
    read_recent: true

remote_write:
  - url: "http://clickvisual:9201/write"
    queue_config:
      capacity: 10000
      max_shards: 1
      max_samples_per_send: 500
```
