### ISSUE TITLE
bug: Helm配置错误

### ISSUE THREAD

**Issue by boomboomxx** [clickvisual/clickvisual#1158]
**Describe the bug**
Helm 包中, `templates/deployment.yaml` 文件配置多了一段, 导致 pod 无法启动
以下为精简配置文件, 多出一段 `command` 命令
该命令会在 docker 镜像启动的时候,自动执行,无需手动在这里加上
且该段命令无任何指定参数,会一直输出 `usage` 信息 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          command:
            - /bin/sh
            - -c
            - ./bin/clickvisual
```

**ClickVisual Running Environment**
- Kubernetes 1.24.12
- Helm v3.12.1
- ClickVisual version:
1.0.1-rc1
- ClickVisual.LOG:
```text
Usage:
  clickvisual [command]

Available Commands:
  agent       启动 clickvisual agent 服务端
  command     启动 clickvisual 命令行
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  server      启动 clickvisual server 服务端
  upload      启动 clickvisual 命令行

Flags:
  -c, --config string   指定配置文件，默认 config/default.toml (default "config/default.toml")
  -h, --help            help for clickvisual

Use "clickvisual [command] --help" for more information about a command.
```
**解决方案**
删除上述 `command` 部分配置即可
