### ISSUE TITLE
日志告警使用 `below` 如果不存在指标时不会满足条件

### ISSUE THREAD

**Issue by laojianzi** [clickvisual/clickvisual#735]
e.g:

`WHEN` `min()` `below` `2`

```sql
CREATE MATERIALIZED VIEW database.table_cacd6b05_e8da_4e02_b1c1_677cbb3e0c5a_227 on cluster 'replicated' TO metrics.samples_local AS
SELECT
  toDate(_time_second_) as date,
  'clickvisual_alert_metrics' as name,
  array('uuid=cacd6b05-e8da-4e02-b1c1-677cbb3e0c5a','filterId=227') as tags,
  toFloat64(count(*)) as val,
  _time_second_ as ts,
  toDateTime(_time_second_) as updated
FROM `database`.`table`
WHERE `_container_name_` = 'app123' AND `level` = 'error'
GROUP BY _time_second_;
```

```yaml
groups:
- name: default
  rules:
  - alert: cacd6b05_e8da_4e02_b1c1_677cbb3e0c5a
    expr: clickvisual_alert_metrics{uuid="cacd6b05-e8da-4e02-b1c1-677cbb3e0c5a",filterId="227"} offset 10s<2
    for: 3m
    labels:
      severity: warning
    annotations:
      summary: "告警 {{ $labels.name }}"
      description: "{{ $labels.desc }}  (当前值: {{ $value }})"
```

当 MATERIALIZED VIEW 一直都是 SELECT 空的 result，一直没有指标产生，Prometheus 查询时也会出现指标空 result 的情况，但空 result 不等于 0，所以告警条件一直都不会满足

但实际上没有出现过在使用场景来说，本质上就是 0 次出现

---

expr 可以将指标不存在也认为是 0，则可以解决这个问题
例如:

```yaml
...
    expr: (clickvisual_alert_metrics{filterId="227",uuid="cacd6b05-e8da-4e02-b1c1-677cbb3e0c5a"} offset 10s or clamp_max(absent(notExists{filterId="227",uuid="cacd6b05-e8da-4e02-b1c1-677cbb3e0c5a"}), 0)) < 2
...
```
