### ISSUE TITLE
[FEATURE]: 钉钉告警希望支持@指定钉钉用户

### ISSUE THREAD

**Issue by hedongfang** [clickvisual/clickvisual#821]
钉钉群告警中，因为告警群中人员较多，希望精准推送到@某一个用户。
[prometheus-webhook-dingtalk](https://github.com/timonwong/prometheus-webhook-dingtalk)支持钉钉@用户
希望clickvisual告警规则选项中支持添加订单用户手机号
```
groups:
- name: default
  rules:
  - alert: ec639018_631c_46e1_959d_5da00911a1d9_70
    expr: clickvisual_alert_metrics{uuid="ec639018-631c-46e1-959d-5da00911a1d9",alarmId="22",filterId="70"} offset 10s>1
    for: 1m
    labels:
      service: dingtalk
      severity: warning
    annotations:
      summary: "告警 {{ $labels.name }}"
      description: "{{ $labels.desc }}  (当前值: {{ $value }})"
      user: "@138xxxxxxxx"
```
